[package]
name = "rework"
version = "0.1.0"
authors = ["Vickenty Fesunov <kent@setattr.net>"]
build = "build.rs"

[build-dependencies]
peg="0.5"

[dependencies]
serde="1.0"
serde_derive="1.0"
docopt="0.8"
